require 'net/http'
require 'nokogiri'
require 'date'

# Метод для извлечения данных о валютных курсах за указанный период
def fetch_currency_rates_for_last_month
  end_date = Date.today
  start_date = end_date.prev_month
  fetch_currency_rates(start_date, end_date)
end

def fetch_currency_rates(start_date, end_date)
  currency_data = []

  (start_date..end_date).each do |date|
    url = "https://www.cbr.ru/scripts/XML_daily.asp?date_req=#{date.strftime('%d/%m/%Y')}"
    response = Net::HTTP.get(URI(url))
    xml_data = Nokogiri::XML(response)

    xml_data.xpath('//ValCurs/Valute').each do |valute|
      char_code = valute.xpath('CharCode').text
      next unless ['USD', 'EUR', 'CNY'].include?(char_code)

      nominal = valute.xpath('Nominal').text.to_i
      value = valute.xpath('Value').text.gsub(',', '.').to_f
      currency_data << { date: date, currency: char_code, rate: value / nominal }
    end
  end

  currency_data
end

def generate_seeds_file(currency_rates)
  File.open('db/seeds.rb', 'w') do |file|
    file.puts "# Autogenerated seeds file for last month currency rates"
    currency_rates.each do |rate|
      file.puts "CurrencyRate.find_or_create_by(date: '#{rate[:date]}', currency: '#{rate[:currency]}') do |currency_rate|"
      file.puts "  currency_rate.rate = #{rate[:rate]}"
      file.puts "end"
    end
  end
end

# Получение данных за последний месяц
currency_rates = fetch_currency_rates_for_last_month

# Генерация seeds.rb
generate_seeds_file(currency_rates)
puts 'Seeds file for the last month has been generated successfully!'
